from __future__ import annotations
from dataclasses import asdict
from datetime import datetime, timezone
from trading_engine.types import TradeSetup
class TradeJournalBuilder:
    def build_entry(self, setup: TradeSetup, screenshot_path: str = "") -> dict:
        return {"created_at":datetime.now(timezone.utc).isoformat(),"symbol":setup.symbol,"direction":setup.direction.value,"entry":str(setup.entry),"stop_loss":str(setup.stop_loss),"tp1":str(setup.take_profit_1),"tp2":str(setup.take_profit_2),"tp3":str(setup.take_profit_3),"score":str(setup.score.total),"reason":setup.explanation,"market_conditions":{"session":setup.session.name,"structure":setup.structure.last_event,"crt_state":setup.crt_range.state},"screenshot":screenshot_path,"lessons":"Generated by deterministic pre-trade process; post-trade lesson added after closure.","audit":setup.audit}
