from decimal import Decimal
from django.conf import settings
from django.db import models
from backend.apps.common.models import BaseModel,Currency
class SubscriptionPlan(BaseModel): code=models.CharField(max_length=32,unique=True); name=models.CharField(max_length=120); price_monthly=models.DecimalField(max_digits=12,decimal_places=2,default=Decimal("0")); currency=models.CharField(max_length=3,choices=Currency.choices,default=Currency.USD); features=models.JSONField(default=dict); limits=models.JSONField(default=dict); is_active=models.BooleanField(default=True)
class Subscription(BaseModel): user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name="subscriptions"); plan=models.ForeignKey(SubscriptionPlan,on_delete=models.PROTECT,related_name="subscriptions"); starts_at=models.DateTimeField(db_index=True); expires_at=models.DateTimeField(db_index=True); status=models.CharField(max_length=32,default="ACTIVE",db_index=True); auto_renew=models.BooleanField(default=False); usage=models.JSONField(default=dict)
class Invoice(BaseModel): user=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.PROTECT,related_name="invoices"); subscription=models.ForeignKey(Subscription,on_delete=models.PROTECT,related_name="invoices",null=True,blank=True); invoice_number=models.CharField(max_length=64,unique=True); amount=models.DecimalField(max_digits=12,decimal_places=2); currency=models.CharField(max_length=3,choices=Currency.choices,default=Currency.USD); status=models.CharField(max_length=32,default="ISSUED",db_index=True); due_at=models.DateTimeField(null=True,blank=True); paid_at=models.DateTimeField(null=True,blank=True)
class Payment(BaseModel): invoice=models.ForeignKey(Invoice,on_delete=models.PROTECT,related_name="payments"); gateway=models.CharField(max_length=64,db_index=True); gateway_reference=models.CharField(max_length=160,blank=True,db_index=True); amount=models.DecimalField(max_digits=12,decimal_places=2); status=models.CharField(max_length=32,default="PENDING",db_index=True); raw_payload=models.JSONField(default=dict)
class Refund(BaseModel): payment=models.ForeignKey(Payment,on_delete=models.PROTECT,related_name="refunds"); amount=models.DecimalField(max_digits=12,decimal_places=2); reason=models.TextField(); status=models.CharField(max_length=32,default="REQUESTED",db_index=True)
class Referral(BaseModel): referrer=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name="referrals_made"); referred=models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE,related_name="referrals_received"); code=models.CharField(max_length=32,db_index=True); reward_status=models.CharField(max_length=32,default="PENDING")
