# Generated by Django 5.2.16 on 2026-07-20 09:16

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=120)),
                ('max_risk_per_trade_pct', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=5)),
                ('max_daily_loss_pct', models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5)),
                ('max_total_drawdown_pct', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('max_open_positions', models.PositiveIntegerField(default=5)),
                ('max_correlation_exposure', models.DecimalField(decimal_places=2, default=Decimal('30.00'), max_digits=5)),
                ('enforce_stop_loss', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_default'], name='risk_riskpr_user_id_76399c_idx')],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
