# Generated by Django 5.2.16 on 2026-07-20 09:16

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(db_index=True, max_length=160)),
                ('model_name', models.CharField(max_length=120)),
                ('prompt_hash', models.CharField(db_index=True, max_length=128)),
                ('input_snapshot', models.JSONField(default=dict)),
                ('analysis', models.TextField()),
                ('confidence', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analyses', to='trading.tradingaccount')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerformanceAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('period_start', models.DateTimeField(db_index=True)),
                ('period_end', models.DateTimeField(db_index=True)),
                ('win_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('loss_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6)),
                ('profit_factor', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('expectancy', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('average_rr', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=12)),
                ('average_hold_minutes', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('max_drawdown', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('equity_curve', models.JSONField(default=list)),
                ('daily_profit', models.JSONField(default=dict)),
                ('weekly_profit', models.JSONField(default=dict)),
                ('monthly_profit', models.JSONField(default=dict)),
                ('yearly_profit', models.JSONField(default=dict)),
                ('trade_distribution', models.JSONField(default=dict)),
                ('heatmap', models.JSONField(default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_analytics', to='trading.tradingaccount')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StrategyStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('strategy_name', models.CharField(db_index=True, max_length=120)),
                ('total_trades', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('net_profit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('metrics', models.JSONField(default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strategy_statistics', to='trading.tradingaccount')),
                ('symbol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='trading.tradingsymbol')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
